{{- if .Values.deployClusterServiceBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: osb-stub
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  url: https://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  insecureSkipTLSVerify: true
{{- if .Values.authenticate}}
  authInfo:
    bearer:
      secretRef:
        namespace: {{.Release.Namespace}}
        name: {{ template "fullname" . }}
{{- end }}
{{- end }}
