{{- $ca := genCA "svc-cat-ca" 3650 }}
{{- $cn := printf "%s-osb-stub" .Release.Name }}
{{- $altName1 := printf "%s-osb-stub.%s" .Release.Name .Release.Namespace }}
{{- $altName2 := printf "%s-osb-stub.%s.svc" .Release.Name .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-osb-stub-cert
  labels:
    app: {{ template "fullname" . }}-osb-stub
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
  