apiVersion: v1
kind: Template
metadata:
  name: osb-stub
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: osb-stub-client

- kind: Secret
  apiVersion: v1
  metadata:
    name: osb-stub
    annotations:
      kubernetes.io/service-account.name: osb-stub-client
  type: kubernetes.io/service-account-token

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: osb-stub
  spec:
    url: https://osb-stub.osb-stub.svc.cluster.local
    caBundle: ${BROKER_CA_CERT}
    authInfo:
      bearer:
        secretRef:
          namespace: ${NAMESPACE}
          name: osb-stub

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: osb-stub

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: osb-stub
  rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: osb-stub
  subjects:
    - kind: ServiceAccount
      name: osb-stub
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: osb-stub

- kind: Service
  apiVersion: v1
  metadata:
    name: osb-stub
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: 'osb-stub-ssl'
    labels:
      app: osb-stub
  spec:
    selector:
      app: osb-stub
    ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: osb-stub
    labels:
      app: osb-stub
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: osb-stub
    template:
      metadata:
        labels:
          app: osb-stub
      spec:
        serviceAccount: osb-stub
        containers:
        - name: service-osb-stub
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8443"
          - -v
          - "4"
          - --logtostderr
          - --tls-cert-file
          - "/var/run/osb-stub/osbstub.crt"
          - --tls-private-key-file
          - "/var/run/osb-stub/osbstub.key"
          - --authenticate-k8s-token
          ports:
          - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/run/osb-stub
            name: osb-stub-ssl
            readOnly: true
        volumes:
        - name: osb-stub-ssl
          secret:
            defaultMode: 420
            secretName: osb-stub-ssl
            items:
            - key: tls.crt
              path: osbstub.crt
            - key: tls.key
              path: osbstub.key

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: quay.io/osb-stub/servicebroker:latest

- description: base64 encoded SSL CA Certificate
  displayName: base64 encoded SSL CA Certificate
  name: BROKER_CA_CERT
  required: true
  value: 

- description: Namespace that the osb stub is deployed to
  displayName: Namespace
  name: NAMESPACE
  value: osb-stub
